# Generated by Django 4.0.5 on 2022-06-11 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPersona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado_dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_estado_dispositivo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Parentesco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_tipo_dispositivo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_propiedad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=15)),
                ('estado_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPersona.estado_dispositivo')),
                ('tipo_dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPersona.tipo_dispositivo')),
            ],
        ),
        migrations.AddField(
            model_name='personas',
            name='parentesco',
            field=models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, to='gestionPersona.parentesco'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_propiedad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestionPersona.tipo_propiedad'),
        ),
    ]
