# Generated by Django 4.0.5 on 2022-06-11 02:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestionPersona', '0003_alter_dispositivo_estado_dispositivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispositivo',
            name='estado_dispositivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPersona.estado_dispositivo'),
        ),
        migrations.AlterField(
            model_name='dispositivo',
            name='tipo_dispositivo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPersona.tipo_dispositivo'),
        ),
        migrations.AlterField(
            model_name='personas',
            name='parentesco',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPersona.parentesco'),
        ),
        migrations.AlterField(
            model_name='propiedad',
            name='tipo_propiedad',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestionPersona.tipo_propiedad'),
        ),
    ]
